spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/dkrperweb?characterEncoding=UTF-8&serverTimezone=GMT%2B8
    username: root
    password: 1234567ch
  cassandra:
    port: 7781
mybatis:
  mapper-locations: classpath:mapper/*.xml
